name: Run Unit and Integration Tests

on:
  push:
    branches: [ exercice-issue ]
  pull_request:
    branches: [ exercice-issue ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests with pytest
      run: |
        export PYTHONPATH=.
        pytest unit_tests/

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests  # Optionnel : exécute les tests d'intégration *après* les tests unitaires

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run integration tests with pytest
      run: |
        export PYTHONPATH=.
        pytest integration_tests/
