name: Build, Push and Scan Docker Image

on: [push, workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: malo350stern
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        run: |
          docker build -t malo350stern/isen-python:dev-${{ github.sha }} -t europe-west1-docker.pkg.dev/sacred-vigil-458212-r5/repositoryofpart5/googleimage:dev-${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push malo350stern/isen-python:dev-${{ github.sha }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.16.0
        with:
          image-ref: malo350stern/isen-python:dev-${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
        continue-on-error: true
  
  
  GoogleAuthentification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Authentification
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.REPOSITORYOFPART5 }}' # Replace with the name of your GitHub Actions secret
      - name: yamlsdkl
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
      
      - uses: 'actions/checkout@v4'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '1046952898526-compute@developer.gserviceaccount.com'
          image: 'europe-west1-docker.pkg.dev/sacred-vigil-458212-r5/repositoryofpart5/googleimage'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'